name = "onibus-rj-ao-vivo"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
account_id = "864c4fd22125f77c95e383c82331b7a4"

[assets]
directory = "../dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[routes]]
pattern = "kbrianps.com/tools/onibus-rj-ao-vivo"
zone_id = "0c431faf60029ddeb333942fbffcc58b"

[[routes]]
pattern = "kbrianps.com/tools/onibus-rj-ao-vivo/*"
zone_id = "0c431faf60029ddeb333942fbffcc58b"

[[routes]]
pattern = "www.kbrianps.com/tools/onibus-rj-ao-vivo"
zone_id = "0c431faf60029ddeb333942fbffcc58b"

[[routes]]
pattern = "www.kbrianps.com/tools/onibus-rj-ao-vivo/*"
zone_id = "0c431faf60029ddeb333942fbffcc58b"

[[routes]]
pattern = "kbrianps.com/.well-known/assetlinks.json"
zone_id = "0c431faf60029ddeb333942fbffcc58b"

[[routes]]
pattern = "www.kbrianps.com/.well-known/assetlinks.json"
zone_id = "0c431faf60029ddeb333942fbffcc58b"

[vars]
ALLOWED_ORIGINS = "https://kbrianps.com,https://www.kbrianps.com"
TWA_PACKAGE_NAME = "com.kbrianps.onibusrjaovivo"
TWA_FINGERPRINTS = ""

[triggers]
crons = ["* * * * *"]

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 45, period = 60 }

[[r2_buckets]]
binding = "ROUTES"
bucket_name = "onibus-rj-routes"

[dev]
port = 8787

[env.dev.vars]
ALLOWED_ORIGINS = "https://kbrianps.com,https://www.kbrianps.com,http://localhost:5173,http://127.0.0.1:5173"
